version: "3.8"


services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13689282250
      POSTGRES_DB: resumedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d resumedb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    environment:
      - DATABASE_URL=postgresql://postgres:13689282250@db:5432/resumedb
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8699:8000"
    volumes:
      - ./:/app
    # 可选：healthcheck 确保 DB 初始化完成再启动后端
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d resumedb -h db"]
      interval: 5s
      retries: 5

volumes:
  pgdata: